---
backend:
  branch: master
  name: git-gateway

media_folder: assets/images/uploads

collections:
  - label: "Всі Сторінки"
    name: pages
    files:
      - label: "Календар"
        name: "calendar"
        file: "_data/calendar.yaml"
        fields:
          - label: "Місяць"
            name: "month"
            widget: "list"
            fields:
              - label: "Дата початку місяця"
                name: "month_date"
                widget: "date"
                format: "MM-YYYY"
              - label: "Публікувати"
                name: "isPublished"
                widget: "boolean"
                default: false
              - label: "День"
                name: "day"
                required: false
                widget: "list"
                fields:
                  - label: "Число"
                    name: "d"
                    widget: "number"
                    min: 1
                    max: 31
                  - label: "Час1"
                    name: "time1"
                    required: false
                    format: "H:mm"
                    widget: "datetime"
                  - label: "Подія1"
                    name: "event1"
                    required: false
                    widget: "string"
                  - label: "Час2"
                    name: "time2"
                    required: false
                    format: "H:mm"
                    widget: "datetime"
                  - label: "Подія2"
                    name: "event2"
                    required: false
                    widget: "string"
                  - label: "Час3"
                    name: "time3"
                    required: false
                    format: "H:mm"
                    widget: "datetime"
                  - label: "Подія3"
                    name: "event3"
                    required: false
                    widget: "string"
                  - label: "Захід"
                    name: "occasion"
                    required: false
                    widget: "string"
  - label: "Новини"
    name: "novyny"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Topic", name: "topic", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Autor", name: "autor", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "DD.MM.YYYY"}
      - {label: "Featured Image", name: "picture", required: false, widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
