backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads

collections:
    - label: "Pages"
      name: "pages"
      files:
          - label: "Navigation bar"
            name: "navbar"
            file: "_data/navigation.yml"
            fields:
                - {label: Item Name, name: name, widget: string}
                - {label: Link, name: link, widget: string}
