---
backend:
  branch: master
  name: git-gateway
collections:
  -
    files:
      -
        fields:
          -
            fields:
              -
                label: Заголовок
                name: title
                widget: string
              -
                label: Автор
                name: autor
                required: false
                widget: string
              -
                format: DD.MM.YYYY
                label: "Дата публікації"
                name: date
                widget: date
              -
                label: Зображення
                name: picture
                required: false
                widget: image
              -
                label: "Перший абзац"
                name: excerpt
                required: false
                widget: markdown
              -
                label: "Текст новини"
                name: text
                widget: markdown
            label: Новини
            name: news
            widget: list
          -
            fields:
              -
                fields:
                  -
                    label: Titel
                    name: title
                    widget: string
                  -
                    label: Autor
                    name: autor
                    required: false
                    widget: string
                  -
                    format: DD.MM.YYYY
                    label: Publikationsdatum
                    name: date
                    widget: date
                  -
                    label: Bild
                    name: picture
                    required: false
                    widget: image
                  -
                    label: "Erster Absatz"
                    name: excerpt
                    required: false
                    widget: markdown
                  -
                    label: "Weiterer Text"
                    name: text
                    widget: markdown
                label: Nachricht
                name: news
                widget: list
            file: _data/de/barbareum.yml
            label: Barbareum
            name: barbareum_de
        file: _data/ua/barbareum.yml
        label: "Barbareum UA/DE"
        name: barbareum_ua
      -
        fields:
          -
            fields:
              -
                label: Заголовок
                name: title
                widget: string
              -
                label: Автор
                name: autor
                required: false
                widget: string
              -
                format: DD.MM.YYYY
                label: "Дата публікації"
                name: date
                widget: date
              -
                label: Зображення
                name: picture
                required: false
                widget: image
              -
                label: "Перший абзац"
                name: excerpt
                required: false
                widget: markdown
              -
                label: "Текст новини"
                name: text
                widget: markdown
            label: Новини
            name: news
            widget: list
        file: _data/ua/news.yml
        label: "Стрічка новин"
        name: news_ua
      -
        fields:
          -
            fields:
              -
                label: Titel
                name: title
                widget: string
              -
                label: Autor
                name: autor
                required: false
                widget: string
              -
                format: DD.MM.YYYY
                label: Publikationsdatum
                name: date
                widget: date
              -
                label: Bild
                name: picture
                required: false
                widget: image
              -
                label: "Erster Absatz"
                name: excerpt
                required: false
                widget: markdown
              -
                label: "Weiterer Text"
                name: text
                widget: markdown
            label: Nachricht
            name: news
            widget: list
        file: _data/de/news.yml
        label: Nachrichten
        name: news_de
    label: "Новини UA/DE"
    name: news_ua_de
  -
    files:
      -
        fields:
          -
            fields:
              -
                label: Назва
                name: name
                widget: string
              -
                label: Лінк
                name: link
                widget: string
            label: "Елемент меню"
            name: navbar
            widget: list
        file: _data/ua/navigation.yml
        label: "Головне Меню"
        name: navbar
      -
        fields:
          -
            fields:
              -
                format: MM-YYYY
                label: "Дата початку місяця"
                name: month_date
                widget: date
              -
                default: false
                label: Публікувати
                name: is_published
                widget: boolean
              -
                label: Оголошення
                name: announcement
                required: false
                widget: string
              -
                fields:
                  -
                    hint: "День місяця"
                    label: Число
                    max: 31
                    min: 1
                    name: d
                    widget: number
                  -
                    fields:
                      -
                        dateFormat: false
                        default: ""
                        format: "H:mm"
                        label: Час
                        name: time
                        widget: datetime
                      -
                        label: Назва
                        name: title
                        required: false
                        widget: string
                    label: Подія
                    name: event
                    required: false
                    widget: list
                  -
                    label: "Додатковий захід"
                    name: occasion
                    required: false
                    widget: string
                label: День
                name: day
                required: false
                widget: list
            label: Місяць
            name: month
            widget: list
        file: _data/ua/calendar.yml
        label: Календар
        name: calendar
      -
        fields:
          -
            fields:
              -
                label: "Заголовок українською"
                name: ua
                required: true
                widget: string
              -
                label: "Заголовок німецькою"
                name: de
                required: true
                widget: string
              -
                label: "Титульне фото"
                name: title_pic
                widget: image
              -
                fields:
                  -
                    label: Фото
                    name: pic
                    widget: image
                label: Колекція
                name: collection
                required: true
                widget: list
            label: Подія
            name: event
            widget: list
        file: _data/events/gallerie.yaml
        label: Галерея
        name: gallerie
      -
        fields:
          -
            fields:
              -
                label: Призначення
                name: subject
                required: true
                widget: string
              -
                format: DD-MM-YYYY
                label: Число
                name: date
                required: true
                widget: date
              -
                label: Необхідно
                name: needed
                required: false
                widget: number
              -
                label: Текст
                name: text
                required: true
                widget: string
              -
                label: Зібрано
                name: collected
                required: false
                widget: number
              -
                label: Картинка
                name: image
                required: true
                widget: image
              -
                fields:
                  -
                    label: "Від кого"
                    name: from
                    required: false
                    widget: string
                  -
                    label: "На кого"
                    name: for
                    required: false
                    widged: string
                  -
                    label: Сума
                    name: amount
                    required: true
                    widget: number
                  -
                    format: DD-MM-YYYY
                    label: Число
                    name: date
                    required: true
                    widget: date
                label: Внески
                name: donations
                widget: list
            label: Пожертва
            name: pozhertva
            widget: list
        file: _data/ua/pozhertvy.yml
        label: Пожертви
        name: pozhertvy_ua
      -
        fields:
          -
            fields:
              -
                label: Zweck
                name: subject
                required: true
                widget: string
              -
                format: DD-MM-YYYY
                label: Datum
                name: date
                required: true
                widget: date
              -
                label: Erforderlich
                name: needed
                required: true
                widget: number
              -
                label: Gesammelt
                name: collected
                required: false
                widget: number
              -
                label: Текст
                name: text
                required: true
                widget: string
              -
                label: Bild
                name: image
                required: false
                widget: image
              -
                fields:
                  -
                    label: Von
                    name: from
                    required: false
                    widget: string
                  -
                    label: "Auf wen"
                    name: for
                    required: false
                    widged: string
                  -
                    label: Summe
                    name: amount
                    required: true
                    widget: number
                  -
                    format: DD-MM-YYYY
                    label: Datum
                    name: date
                    required: true
                    widget: date
                label: Beiträge
                name: donations
                widget: list
            label: Spende
            name: pozhertva
            widget: list
        file: _data/de/pozhertvy.yml
        label: Spenden
        name: pozhertvy_de
    label: "Всі Сторінки"
    name: pages
media_folder: assets/images/uploads
