---
backend:
  branch: master
  name: git-gateway

media_folder: assets/images/uploads
publish_mode: editorial_workflow

collections:
  - label: "Всі Сторінки"
    name: pages
    files:
      - label: "Головне Меню"
        name: "navbar"
        file: "_data/navigation.yml"
        fields:
          - label: Елемент Меню
            name: navbar
            widget: list
            fields:
              - {label: Назва, name: name, widget: string}
              - {label: Лінк, name: link, widget: string}
      - label: Розклад
        name: timetable
        file: _data/table.yml
        fields:
          - label: "Елемент Меню"
            name: timetable
            widget: list
            fields:
              - label: День
                name: day
                widget: string
              - label: Місяць
                name: month
                widget: string
              - label: Час1
                name: time1
                widget: string
              - label: Подія1
                name: event1
                widget: string
              - label: Час2
                name: time2
                widget: string
              - label: Подія2
                name: event2
                widget: string
              - label: Час
                name: time3
                widget: string
              - label: Подія3
                name: event3
                widget: string
              - label: Час4
                name: time4
                widget: string
              - label: Подія4
                name: event4
                widget: string
              - label: Час5
                name: time5
                widget: string
              - label: Подія5
                name: event5
                widget: string
              - label: Захід
                name: occasion
                widget: string
  - label: "Новини"
    name: "novyny"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Topic", name: "topic", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Autor", name: "autor", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "DD.MM.YYYY"}
      - {label: "Featured Image", name: "picture", required: false, widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
