--- 
backend: 
  branch: master
  name: git-gateway
  
media_folder: assets/images/uploads
publish_mode: editorial_workflow

collections: 
  - label: "Всі Сторінки"
    name: pages
    files: 
      - label: "Головне Меню"
        name: "navbar"
        file: "_data/navigation.yml"
        fields:
            - label: Елемент Меню
              name: navbar
              widget: list
              fields:
                 - {label: Назва, name: name, widget: string}
                 - {label: Лінк, name: link, widget: string}
      - label: Розклад
        name: timetable
        file: _data/table.yml
        fields: 
          - label: "Елемент Меню"
            name: timetable
            widget: list
            fields: 
              - 
                label: День
                name: day
                widget: string
              - 
                label: Місяць
                name: month
                widget: string
              - 
                label: Час1
                name: time1
                widget: string
              - 
                label: Подія1
                name: event1
                widget: string
              - 
                label: Час2
                name: time2
                widget: string
              - 
                label: Подія2
                name: event2
                widget: string
              - 
                label: Час
                name: time3
                widget: string
              - 
                label: Подія3
                name: event3
                widget: string
              - 
                label: Захід
                name: occasion
                widget: string
    
    
