---
backend:
  branch: master
  name: git-gateway

media_folder: assets/images/uploads

collections:
  - label: Всі Сторінки
    name: pages
    files:
      - label: Головне Меню
        name: navbar
        file: _data/ua/navigation.yml
        fields:
          - label: Елемент меню
            name: navbar
            widget: list
            fields:
              - {label: Назва, name: name, widget: string}
              - {label: Лінк, name: link, widget: string}
      - label: Календар
        name: calendar
        file: _data/ua/calendar.yml
        fields:
          - label: Місяць
            name: month
            widget: list
            fields:
              - label: Дата початку місяця
                name: month_date
                widget: date
                format: 'MM-YYYY'
              - label: Публікувати
                name: is_published
                widget: boolean
                default: false
              - label: Оголошення
                name: announcement
                widget: string
                required: false
              - label: День
                name: day
                required: false
                widget: list
                fields:
                  - label: Число
                    name: d
                    widget: number
                    min: 1
                    max: 31
                    hint: День місяця
                  - label: Подія
                    name: event
                    required: false
                    widget: list
                    fields:
                      - label: Час
                        name: time
                        widget: datetime
                        format: 'H:mm'
                        dateFormat: false
                        default: ""
                      - label: Назва
                        name: title
                        required: false
                        widget: string
                  - label: Додатковий захід
                    name: occasion
                    widget: string
                    required: false
      - label: Новини UA/DE
        name: news_ua_de
        fields:
          - label: Стрічка новин
            name: news_ua
            file: _data/ua/news.yml
            fields:
              - label: Новини
                name: news
                widget: list
                fields:
                  - {label: Заголовок, name: title, widget: string}
                  - {label: Автор, name: autor, required: false, widget: string}
                  - {label: Дата публікації, name: date, widget: date, format: 'DD.MM.YYYY'}
                  - {label: Зображення, name: picture, required: false, widget: image}
                  - {label: Перший абзац, name: excerpt, required: false, widget: markdown}
                  - {label: Текст новини, name: text, widget: markdown}
          - label: Nachrichten
            name: news_de
            file: _data/de/news.yml
            fields:
              - label: Nachricht
                name: news
                widget: list
                fields:
                  - {label: Titel, name: title, widget: string}
                  - {label: Autor, name: autor, required: false, widget: string}
                  - {label: Publikationsdatum, name: date, widget: date, format: 'DD.MM.YYYY'}
                  - {label: Bild, name: picture, required: false, widget: image}
                  - {label: Erster Absatz, name: excerpt, required: false, widget: markdown}
                  - {label: Weiterer Text, name: text, widget: markdown}
      - label: Галерея
        name: gallerie
        file: _data/events/gallerie.yaml
        fields:
          - label: Подія
            name: event
            widget: list
            fields:
              - label: Заголовок українською
                name: ua
                widget: string
                required: true
              - label: Заголовок німецькою
                name: de
                widget: string
                required: true
              - label: Титульне фото
                name: title_pic
                widget: image
              - label: Колекція
                name: collection
                required: true
                widget: list
                fields:
                  - label: Фото
                    name: pic
                    widget: image
      - label: Пожертви
        name: pozhertvy_ua
        file: _data/ua/pozhertvy.yml
        fields:
          - label: Пожертва
            name: pozhertva
            widget: list
            fields:
              - label: Призначення
                name: subject
                widget: string
                required: true
              - label: Необхідно
                name: needed
                widget: number
                required: true
              - label: Внески
                name: donations
                widget: list
                fields:
                  - label: Від кого
                    name: from
                    widget: string
                    required: true
                  - label: Сума
                    name: amount
                    widget: number
                    required: true
      - label: Spenden
        name: pozhertvy_de
        file: _data/de/pozhertvy.yml
        fields:
          - label: Spende
            name: pozhertva
            widget: list
            fields:
              - label: Zweck
                name: subject
                widget: string
                required: true
              - label: Erforderlich
                name: needed
                widget: number
                required: true
              - label: Beiträge
                name: donations
                widget: list
                fields:
                  - label: Von
                    name: from
                    widget: string
                    required: true
                  - label: Summe
                    name: amount
                    widget: number
                    required: true


