---
backend:
  branch: master
  name: git-gateway

media_folder: assets/images/uploads

collections:
  - label: Всі Сторінки
    name: pages
    files:
      - label: Головне Меню
        name: navbar
        file: _data/navigation.yml
        fields:
          - label: Елемент меню
            name: navbar
            widget: list
            fields:
              - {label: Назва, name: name, widget: string}
              - {label: Лінк, name: link, widget: string}
      - label: Календар
        name: calendar
        file: _data/calendar.yml
        fields:
          - label: Місяць
            name: month
            widget: list
            fields:
              - label: Дата початку місяця
                name: month_date
                widget: date
                format: 'MM-YYYY'
              - label: Публікувати
                name: is_published
                widget: boolean
                default: false
              - label: День
                name: day
                required: false
                widget: list
                fields:
                  - label: Число
                    name: d
                    widget: number
                    min: 1
                    max: 31
                    hint: День місяця
                  - label: Подія
                    name: event
                    required: false
                    widget: list
                    fields:
                      - label: Час
                        name: time
                        widget: datetime
                        format: 'H:mm'
                        dateFormat: false
                        default: ""
                      - label: Назва
                        name: title
                        widget: string
                  - label: Додатковий захід
                    name: occasion
                    widget: string
                    required: false
      - label: Стрічка новин
        name: news
        file: _data/news.yml
        fields:
          - label: Новини
            name: news
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Autor, name: autor, widget: string}
              - {label: Publish Date, name: date, widget: date, format: 'DD.MM.YYYY'}
              - {label: Featured Image, name: picture, required: false, widget: image}
              - {label: First Absatz, name: excerpt, widget: markdown}
              - {label: Message, name: text, widget: markdown}
